.TH AlignWall.h 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AlignWall.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fR
.br
\fC#include "gyro.h"\fR
.br
\fC#include "wheel.h"\fR
.br
\fC#include "usonic.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBAlignWall\fR"
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "const int \fBAlignDistance\fR = 170"
.br
.in -1c
.SH VARIABLE DOCUMENTATION
.PP 
.SS const int AlignDistance = 170
.PP
Definition at line 25 of file AlignWall.h.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.