.TH dsp_str 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsp_str \- 
.SH SYNOPSIS
.br
.PP
\fC#include <speed.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "struct \fBspeed_parm_struct\fR \fBspeed\fR [2]"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS struct \fBspeed_parm_struct\fR dsp_str::speed[2]
.PP
Definition at line 15 of file speed.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.