.TH GoStraight.h 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GoStraight.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fR
.br
\fC#include "gyro.h"\fR
.br
\fC#include "wheel.h"\fR
.br
\fC#include "usonic.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBGoStraight\fR"
.br
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.