.TH gyro.cc 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyro.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include "dfl.h"\fR
.br
\fC#include "ioLib.h"\fR
.br
\fC#include "tyLib.h"\fR
.br
\fC#include "stdio.h"\fR
.br
\fC#include "gyro.h"\fR
.br
.SS Defines

.in +1c
.ti -1c
.RI "#define \fB_MODULE_NAME_\fR  \fBgyro\fR"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define _MODULE_NAME_  \fBgyro\fR
.PP
Definition at line 14 of file gyro.cc.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.