.TH MonitorSide.h 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MonitorSide.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "usonic.h"\fR
.br
\fC#include "gyro.h"\fR
.br
\fC#include "wheel.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBMonitorSide\fR"
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "const int \fBSideZone\fR = 50"
.br
.ti -1c
.RI "const int \fBSideMaxZone\fR = 200"
.br
.in -1c
.SH VARIABLE DOCUMENTATION
.PP 
.SS const int SideMaxZone = 200
.PP
Definition at line 24 of file MonitorSide.h.
.SS const int SideZone = 50
.PP
Definition at line 23 of file MonitorSide.h.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.