.TH MonitorDoor.h 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MonitorDoor.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "usonic.h"\fR
.br
\fC#include "gyro.h"\fR
.br
\fC#include "wheel.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBMonitorDoor\fR"
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "const int \fBTHRESHOLD\fR = 130"
.br
.ti -1c
.RI "const int \fBupTHRESHOLD\fR = 250"
.br
.ti -1c
.RI "const int \fBendDOOR\fR = 70"
.br
.in -1c
.SH VARIABLE DOCUMENTATION
.PP 
.SS const int THRESHOLD = 130
.PP
Definition at line 19 of file MonitorDoor.h.
.SS const int endDOOR = 70
.PP
Definition at line 21 of file MonitorDoor.h.
.SS const int upTHRESHOLD = 250
.PP
Definition at line 20 of file MonitorDoor.h.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.