.TH MonitorFront.h 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MonitorFront.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "usonic.h"\fR
.br
\fC#include "gyro.h"\fR
.br
\fC#include "wheel.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBMonitorFront\fR"
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "const int \fBFrontZone\fR = 50"
.br
.in -1c
.SH VARIABLE DOCUMENTATION
.PP 
.SS const int FrontZone = 50
.PP
Definition at line 23 of file MonitorFront.h.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.