.TH robot.h 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robot.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "gyro.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBwheel\fR"
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "const float \fBMaxSpeed\fR = 1.0"
.br
.ti -1c
.RI "const float \fBMaxTurn\fR = 1.0"
.br
.ti -1c
.RI "const float \fBMaxAcc\fR = 0.2"
.br
.ti -1c
.RI "const float \fBMaxRAcc\fR = 0.2"
.br
.ti -1c
.RI "const float \fBSpeedScaler\fR = 150.0"
.br
.in -1c
.SH VARIABLE DOCUMENTATION
.PP 
.SS const float MaxAcc = 0.2
.PP
Definition at line 8 of file robot.h.
.SS const float MaxRAcc = 0.2
.PP
Definition at line 9 of file robot.h.
.SS const float MaxSpeed = 1.0
.PP
Definition at line 6 of file robot.h.
.SS const float MaxTurn = 1.0
.PP
Definition at line 7 of file robot.h.
.SS const float SpeedScaler = 150.0
.PP
Definition at line 10 of file robot.h.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.