.TH speed_parm_struct 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
speed_parm_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <speed.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBmode\fR"
.br
.ti -1c
.RI "int \fBkp\fR"
.br
.ti -1c
.RI "int \fBki\fR"
.br
.ti -1c
.RI "int \fBspeed\fR"
.br
.ti -1c
.RI "int \fBcur_pos\fR"
.br
.ti -1c
.RI "int \fBcur_vel\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int speed_parm_struct::cur_pos
.PP
Definition at line 10 of file speed.h.
.SS int speed_parm_struct::cur_vel
.PP
Definition at line 11 of file speed.h.
.SS int speed_parm_struct::ki
.PP
Definition at line 8 of file speed.h.
.SS int speed_parm_struct::kp
.PP
Definition at line 7 of file speed.h.
.SS int speed_parm_struct::mode
.PP
Definition at line 6 of file speed.h.
.SS int speed_parm_struct::speed
.PP
Definition at line 9 of file speed.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.