.TH usonic.h 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usonic.h \- 
.SH SYNOPSIS
.br
.PP
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBusonic\fR"
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "const int \fBMaxSonars\fR = 16"
.br
.in -1c
.SH VARIABLE DOCUMENTATION
.PP 
.SS const int MaxSonars = 16
.PP
Definition at line 4 of file usonic.h.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.