.TH wtest.cc 3 "29 May 2002" "HulkRobot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wtest.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include "dfl.h"\fR
.br
\fC#include "mvPort.h"\fR
.br
\fC#include "wtest.h"\fR
.br
.SS Defines

.in +1c
.ti -1c
.RI "#define \fB_MODULE_NAME_\fR  \fBwtest\fR"
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "const float \fBMaxSpeed\fR = 1.0"
.br
.ti -1c
.RI "const float \fBTargetSpeed\fR = 0.1"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define _MODULE_NAME_  \fBwtest\fR
.PP
Definition at line 1 of file wtest.cc.
.SH VARIABLE DOCUMENTATION
.PP 
.SS const float MaxSpeed = 1.0
.PP
Definition at line 8 of file wtest.cc.
.SS const float TargetSpeed = 0.1
.PP
Definition at line 9 of file wtest.cc.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for HulkRobot from the source code.